'use strict';
const $ = id => document.getElementById(id);
let token = '', identity = null, selected = null, current = null, portfolio = [], busy = false;
function node(tag, text, className) { const el = document.createElement(tag); if (text !== undefined) el.textContent = text; if (className) el.className = className; return el; }
function notice(text, error = false) { $('message').textContent = text; $('message').classList.toggle('error', error); }
async function api(path, options = {}) { const headers = {Authorization: `Bearer ${token}`, ...options.headers}; if (options.body && !(options.body instanceof FormData)) headers['Content-Type'] = 'application/json'; const response = await fetch(path, {...options, headers}); const data = await response.json(); if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : 'Input failed validation. Check required fields and policy.'); return data; }
function action(id, handler) { $(id).addEventListener('submit', async e => { e.preventDefault(); if(busy) return; busy = true; try { await handler(); } catch(error) { notice(error.message, true); } finally { busy = false; } }); }
function click(id, handler) { $(id).addEventListener('click', async () => { try { await handler(); } catch(error) { notice(error.message, true); } }); }
function tenderPath(suffix = '') { return `/api/tenders/${encodeURIComponent(selected)}${suffix}`; }
function selectOptions(id, values) { $(id).replaceChildren(...values.map(([value, label]) => { const option = node('option', label); option.value = value; return option; })); }
async function refresh() {
  $("create-tender").hidden = identity?.role !== "admin";
  $("bid-form").hidden = !["admin", "evaluator"].includes(identity?.role);
  $("upload-form").hidden = !["admin", "evaluator"].includes(identity?.role);
  $("accept-fact").hidden = identity?.role !== "evaluator"; portfolio = (await api('/api/tenders')).tenders; $('metric-total').textContent = portfolio.length; $('metric-active').textContent = portfolio.filter(t => t.state === 'ACTIVE').length; $('metric-low').textContent = portfolio.filter(t => t.low_participation).length; $('metric-approved').textContent = portfolio.filter(t => t.state === 'APPROVED').length; renderPortfolio(); if (selected) await loadTender(selected); }
function renderPortfolio() { const entries = portfolio.filter(t => $('portfolio-filter').value !== 'low' || t.low_participation); $('tender-list').replaceChildren(...entries.map(t => { const button = node('button', t.title, `tender-card${selected === t.id ? ' selected' : ''}`); button.append(node('small', `${t.id} · ${t.bidder_count} bidders · ${t.state}`)); button.addEventListener('click', () => loadTender(t.id).catch(e => notice(e.message,true))); return button; })); if (!entries.length) $('tender-list').append(node('p', 'No tenders match this view.', 'muted')); }
async function loadTender(id) { selected = id; current = await api(tenderPath()); renderPortfolio(); $('empty-state').hidden = true; $('tender-workspace').hidden = false; $('tender-title').textContent = current.title; $('tender-state').textContent = `${current.id} / ${current.state}`; $('tender-revision').textContent = `REVISION ${current.revision}`; $('tender-meta').textContent = `${current.agency} · Closing ${current.closing_date} · ${current.currency}`; $('policy').textContent = JSON.stringify(current.criteria, null, 2); const bidders = current.bids.map(b => [b.id, `${b.bidder} (${b.id})`]); selectOptions('upload-bid', [['', 'Tender document'], ...bidders]); selectOptions('fact-bid', bidders); selectOptions('fact-criterion', current.criteria.map(c=>[c.id, `${c.id}: ${c.description}`])); selectOptions('fact-document', current.documents.filter(d=>d.bid_id).map(d=>[d.id, `${d.filename} (${d.bid_id})`])); const latest = current.evaluations[0]; const rows = latest ? latest.report.bids : current.bids.map(b=>({bidder:b.bidder,status:'NOT_EVALUATED'})); $('bid-rows').replaceChildren(...rows.map(b=>{ const tr = node('tr'); [b.bidder,b.status,b.score ?? '—',b.rank ?? '—',b.commercial_total ?? '—',[...(b.missing||[]),...(b.eligibility_failures||[]),...(b.risk_flags||[])].join(', ') || '—'].forEach(v=>tr.append(node('td',v))); return tr; })); if (!rows.length) { const tr=node('tr'); const td=node('td','No bids yet. Add a bidder to begin.'); td.colSpan=6; tr.append(td); $('bid-rows').append(tr); } renderEvaluations(); renderDocuments(); ['evaluate'].forEach(id => $(id).disabled = identity.role !== 'evaluator' || current.state === 'APPROVED'); notice(`Loaded ${current.id}. ${latest && latest.revision !== current.revision ? 'Latest evaluation is stale; evidence has changed.' : 'Evidence must be reviewed before scoring.'}`); }
function renderEvaluations() { $('evaluation-history').replaceChildren(...current.evaluations.slice(0,5).map(e=>{ const card=node('div', undefined,'review-card'); card.append(node('strong',`${e.state} · Revision ${e.revision}`),node('p',`${e.id} · ${e.report.created_at} · ${e.report.decision}`)); if(identity.role === 'reviewer' && e.state === 'PENDING_REVIEW') { const note=node('textarea'); note.placeholder='Independent review / decision rationale (at least 10 characters)'; note.setAttribute('aria-label','Decision rationale'); card.append(note); for(const mode of ['approve','reject']) { const button=node('button',`${mode[0].toUpperCase()+mode.slice(1)} evaluation`); button.addEventListener('click',async()=>{ try{await api(tenderPath(`/evaluations/${e.id}/decision`),{method:'POST',body:JSON.stringify({action:mode,comment:note.value,expected_revision:e.revision})}); await refresh();}catch(error){notice(error.message,true);} }); card.append(button); } } const details=node('details'); details.append(node('summary','Inspect scoring breakdown and evidence'),node('pre',JSON.stringify(e.report.bids,null,2))); card.append(details); return card; })); }
function renderDocuments() { $('document-list').replaceChildren(...current.documents.map(d=>{ const card=node('div',undefined,'evidence-card'); card.append(node('strong',d.filename),node('p',`Scope: ${d.bid_id || 'Tender'} · SHA-256: ${d.sha256}`)); const button=node('button','Open extracted pages'); button.addEventListener('click',async()=>{try{const doc=await api(tenderPath(`/documents/${d.id}`)); $('document-preview').textContent=doc.pages.map(p=>`PAGE ${p.page}\n${p.text}`).join('\n\n'); $('document-preview').hidden=false;}catch(error){notice(error.message,true);}}); card.append(button); return card; })); }
action('login-form', async()=>{token=$('token').value; $('token').value=''; try{identity=await api('/api/me');}catch(error){token=''; throw error;} $('identity').textContent=`${identity.user_id} · ${identity.role}`; await refresh(); notice('Connected. Select a tender or create one as admin.');});
click('logout',()=>{token=''; identity=null; selected=null; current=null; portfolio=[]; $('tender-workspace').hidden=true; $('empty-state').hidden=false; $('identity').textContent='Disconnected. Credentials cleared.'; $('tender-list').replaceChildren(); for(const id of ['metric-total','metric-active','metric-low','metric-approved']) $(id).textContent='—'; notice('Disconnected.');});
click('refresh',refresh); $('portfolio-filter').addEventListener('change',renderPortfolio);
action('create-form',async()=>{const body=JSON.parse($('tender-json').value); await api('/api/tenders',{method:'POST',body:JSON.stringify(body)}); selected=body.id; await refresh();});
action('bid-form',async()=>{await api(tenderPath('/bids'),{method:'POST',body:JSON.stringify({id:$('bid-id').value,bidder:$('bid-name').value})}); $('bid-form').reset(); await refresh();});
action('upload-form',async()=>{const form=new FormData(); form.append('file',$('pdf-file').files[0]); const bid=$('upload-bid').value; const result=await api(tenderPath(`/documents${bid ? '?bid_id='+encodeURIComponent(bid) : ''}`),{method:'POST',body:form}); await refresh(); notice(result.duplicate?'Identical document already exists.':`Document extracted. Malware scanner: ${result.scanner}.`);});
action('fact-form',async()=>{const body={criterion_id:$('fact-criterion').value,value:$('fact-value').value,document_id:$('fact-document').value,page:Number($('fact-page').value),quote:$('fact-quote').value,confidence:Number($('fact-confidence').value),origin:'human',producer:'human-review',review_note:$('fact-note').value}; await api(tenderPath(`/bids/${encodeURIComponent($('fact-bid').value)}/facts`),{method:'POST',body:JSON.stringify(body)}); await refresh(); notice('Reviewed fact appended. Previous evidence remains auditable.');});
click('evaluate',async()=>{await api(tenderPath('/evaluate'),{method:'POST',body:JSON.stringify({idempotency_key:crypto.randomUUID()})}); await refresh();});
action('search-form',async()=>{const result=await api(tenderPath(`/search?q=${encodeURIComponent($('search-query').value)}`)); $('search-results').replaceChildren(...result.matches.map(m=>{const card=node('div',undefined,'evidence-card'); card.append(node('strong',`Page ${m.page} · ${m.bid_id||'Tender'} · ${m.retrieval_method}`),node('p',m.text),node('small',`Document ${m.document_id} / ${m.section}`)); return card;})); if(!result.matches.length) $('search-results').append(node('p','Insufficient evidence. No answer was invented.'));});
click('load-audit',async()=>{$('audit-output').textContent=JSON.stringify(await api(tenderPath('/audit')),null,2);});
document.querySelectorAll('[data-panel]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==button.dataset.panel); document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b===button));}));
document.querySelector('[data-panel="overview"]').classList.add('active');
$('tender-json').value=JSON.stringify({id:'TND-001',title:'Digital records implementation',agency:'Example evaluation committee',closing_date:'2030-12-31',currency:'INR',criteria:[{id:'EL-01',description:'Minimum five years of relevant experience',category:'eligibility',method:'at_least',target:'5',weight:'0'},{id:'TECH-01',description:'Reviewed technical score out of 100',category:'technical',method:'higher',target:'100',weight:'60'},{id:'COST-01',description:'Total comparable commercial offer in INR',category:'commercial',method:'lower',target:'1',weight:'40'}]},null,2);
